package com.studio.domain;
// Generated Apr 2, 2019 8:12:18 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "studio")
public class Address implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long addrId;
	private long custId;
	private String address1;
	private String address2;
	private Integer addrTypeId;
	private Integer countryId;
	private Integer stateId;
	private String city;
	private Integer areaId;
	private Integer pin;
	private Date createdDate;
	private Date udpatedDate;

	public Address() {
	}

	public Address(long addrId, long custId) {
		this.addrId = addrId;
		this.custId = custId;
	}

	public Address(long addrId, long custId, String address1, String address2, Integer addrTypeId, Integer countryId,
			Integer stateId, String city, Integer areaId, Integer pin, Date createdDate, Date udpatedDate) {
		this.addrId = addrId;
		this.custId = custId;
		this.address1 = address1;
		this.address2 = address2;
		this.addrTypeId = addrTypeId;
		this.countryId = countryId;
		this.stateId = stateId;
		this.city = city;
		this.areaId = areaId;
		this.pin = pin;
		this.createdDate = createdDate;
		this.udpatedDate = udpatedDate;
	}

	@Id

	@Column(name = "addr_id", unique = true, nullable = false)
	public long getAddrId() {
		return this.addrId;
	}

	public void setAddrId(long addrId) {
		this.addrId = addrId;
	}

	@Column(name = "cust_id", nullable = false)
	public long getCustId() {
		return this.custId;
	}

	public void setCustId(long custId) {
		this.custId = custId;
	}

	@Column(name = "address1", length = 100)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 100)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "addr_type_id")
	public Integer getAddrTypeId() {
		return this.addrTypeId;
	}

	public void setAddrTypeId(Integer addrTypeId) {
		this.addrTypeId = addrTypeId;
	}

	@Column(name = "country_id")
	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	@Column(name = "state_id")
	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	@Column(name = "city", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "area_id")
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	@Column(name = "pin")
	public Integer getPin() {
		return this.pin;
	}

	public void setPin(Integer pin) {
		this.pin = pin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "udpated_date", length = 10)
	public Date getUdpatedDate() {
		return this.udpatedDate;
	}

	public void setUdpatedDate(Date udpatedDate) {
		this.udpatedDate = udpatedDate;
	}

}
