package com.studio.domain;


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "control_table", catalog = "studio")
public class ControlTable implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date lastLoginDate;
	public ControlTable() {
		
		// TODO Auto-generated constructor stub
	}
	public ControlTable(Integer id, Date lastLoginDate) {
		this.id = id;
		this.lastLoginDate = lastLoginDate;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	@Column(name = "last_login_date", unique = true, nullable = false)
	public Date getLastLoginDate() {
		return lastLoginDate;
	}
	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}
	
	
	
	
}
