package com.studio.domain;
// Generated Mar 20, 2019 11:51:48 PM by Hibernate Tools 5.2.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.studio.utils.DateUtils;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "studio")
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public long custId;
	private String firstName;
	private String lastName;
	private Date dob;
	private String eamil;
	private String mobileNo;
	private String studioName;
	private String phoneNo;
	private Integer custType;
	private Integer rateType;
	private Integer depotId;
	private Double creditBalance=0.0;
	private Double creditLimit=0.0;
	private Integer creditDays=0;
	private String gstNo;
	private Date createdDate;
	private Date updatedDate;
	//private List<Area> area = new ArrayList<Area>();
	private List<Address> address = new ArrayList<Address>();
	private List<Order> orders = new ArrayList<Order>();
	private String strDob;
	private List<JobAllocation> jobAllocations= new ArrayList<JobAllocation>();
	private String addNew;
	private boolean editMode;
	private String address1;
	private String address2;
	private String area;
	private int days;
	//private List<CustomerDetail> customerDetails= new ArrayList<CustomerDetail>();

	public Customer() {
	}

	public Customer(long custId, String firstName) {
		this.custId = custId;
		this.firstName = firstName;
	}

	public Customer(long custId, String firstName, String lastName, Date dob, String eamil, String mobileNo,
			String studioName, String phoneNo, Integer custType, Integer rateType, Integer depotId,
			Double creditBalance, Double creditLimit, Integer creditDays, String gstNo, Date createdDate,
			Date updatedDate/*, int days*/) {
		this.custId = custId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.dob = dob;
		this.eamil = eamil;
		this.mobileNo = mobileNo;
		this.studioName = studioName;
		this.phoneNo = phoneNo;
		this.custType = custType;
		this.rateType = rateType;
		this.depotId = depotId;
		this.creditBalance = creditBalance;
		this.creditLimit = creditLimit;
		this.creditDays = creditDays;
		this.gstNo = gstNo;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	/*	this.days=days;*/
	}

	public Customer(long custId,String area,/*int  days,*/ String address1, String address2, String firstName,String eamil,String mobileNo, List<Address> Address,Integer creditDays,Double creditBalance,Double creditLimit)
	{
		this.custId = custId;
		this.firstName = firstName;
		this.eamil = eamil;
		this.mobileNo = mobileNo;	
		this.address=Address;
		this.creditBalance = creditBalance;
		this.creditLimit = creditLimit;
		this.creditDays = creditDays;
		this.address1=address1;
		this.address2=address2;
		this.setArea(area);
	/*	this.days=days; */
			}

	
	
	@Id
	@Column(name = "cust_id", unique = true, nullable = false)
	public long getCustId() {
		return this.custId;
	}

	public void setCustId(long custId) {
		this.custId = custId;
	}

	@Column(name = "first_name", nullable = false, length = 40)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 40)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
		this.strDob = DateUtils.toDate(dob);
	}

	@Column(name = "eamil", length = 100)
	public String getEamil() {
		return this.eamil;
	}

	public void setEamil(String eamil) {
		this.eamil = eamil;
	}

	@Column(name = "mobile_no", length = 10)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "studio_name", length = 100)
	public String getStudioName() {
		return this.studioName;
	}

	public void setStudioName(String studioName) {
		this.studioName = studioName;
	}

	@Column(name = "phone_no", length = 12)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "cust_type")
	public Integer getCustType() {
		return this.custType;
	}

	public void setCustType(Integer custType) {
		this.custType = custType;
	}
	
	
	@Column(name = "rate_type")
	public Integer getRateType() {
		return this.rateType;
	}

	public void setRateType(Integer rateType) {
		this.rateType = rateType;
	}

	@Column(name = "depot_id")
	public Integer getDepotId() {
		return this.depotId;
	}

	public void setDepotId(Integer depotId) {
		this.depotId = depotId;
	}

	@Column(name = "credit_balance", precision = 22, scale = 0)
	public Double getCreditBalance() {
		return this.creditBalance;
	}

	public void setCreditBalance(Double creditBalance) {
		this.creditBalance = creditBalance;
	}

	@Column(name = "credit_limit", precision = 22, scale = 0)
	public Double getCreditLimit() {
		return this.creditLimit;
	}

	public void setCreditLimit(Double creditLimit) {
		this.creditLimit = creditLimit;
	}
	
	@Column(name = "credit_days")
	public Integer getCreditDays() {
		return this.creditDays;
	}

	public void setCreditDays(Integer creditDays) {
		this.creditDays = creditDays;
	}
	
	@Column(name = "gst_no", length = 20)
	public String getGstNo() {
		return this.gstNo;
	}

	public void setGstNo(String gstNo) {
		this.gstNo = gstNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the address
	 */
	@Transient
	public List<Address> getAddress() {
		return address;
	}

	/**
	 * @param address the address to set
	 */
	public void setAddress(List<Address> address) {
		this.address = address;
	}

	/**
	 * @return the orders
	 */
	@Transient
	public List<Order> getOrders() {
		return orders;
	}

	/**
	 * @param orders the orders to set
	 */
	public void setOrders(List<Order> orders) {
		this.orders = orders;
	}

	/**
	 * @return the strDob
	 */
	@Transient
	public String getStrDob() {
		return strDob;
	}

	/**
	 * @param strDob the strDob to set
	 */
	public void setStrDob(String strDob) {
		this.strDob = strDob;
		this.dob = DateUtils.toDate(strDob);
	}

	/**
	 * @return the jobAllocations
	 */
	@Transient
	public List<JobAllocation> getJobAllocations() {
		return jobAllocations;
	}

	/**
	 * @param jobAllocations the jobAllocations to set
	 */
	public void setJobAllocations(List<JobAllocation> jobAllocations) {
		this.jobAllocations = jobAllocations;
	}

	/**
	 * @return the addNew
	 */
	@Transient
	public String getAddNew() {
		return addNew;
	}

	/**
	 * @param addNew the addNew to set
	 */
	public void setAddNew(String addNew) {
		this.addNew = addNew;
	}

	/**
	 * @return the editMode
	 */
	@Transient
	public boolean isEditMode() {
		return editMode;
	}

	/**
	 * @param editMode the editMode to set
	 */
	public void setEditMode(boolean editMode) {
		this.editMode = editMode;
	}

	@Transient
	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}
	@Transient
	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}
	@Transient
	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}



/*	public Integer getDays() {
		return days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}
*/
	
}
