package com.studio.domain;
// Generated Apr 2, 2019 6:24:46 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.studio.utils.DateUtils;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "studio")
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long empId;
	private String name;
	private Date dob;
	private Integer depotId;
	private Integer roleId;
	private Double advance=0.0;
	private Double salary=0.0;
	private Double incentive = 0.0;
	private String mobileNo;
	private String address1;
	private String address2;
	private String city;
	private String eamil;
	private String username;
	private String password;
	private Date createdDate;
	private Date updatedDate;
	private String strDob;
	private boolean editMode;
	private Integer jobOpenCount;

	public Employee() {
	}

	public Employee(long empId, String name) {
		this.empId = empId;
		this.name = name;
	}

	public Employee(long empId, String name, Date dob, Integer depotId, Integer roleId, Double advance, Double salary,
			Double incentive, String mobileNo, String address1, String address2, String city, String eamil,
			String username, String password, Date createdDate, Date updatedDate,Integer jobOpenCount) {
		this.empId = empId;
		this.name = name;
		this.dob = dob;
		this.depotId = depotId;
		this.roleId = roleId;
		this.advance = advance;
		this.salary = salary;
		this.incentive = incentive;
		this.mobileNo = mobileNo;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.eamil = eamil;
		this.username = username;
		this.password = password;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.jobOpenCount=jobOpenCount;
	}

	@Id

	@Column(name = "emp_id", unique = true, nullable = false)
	public long getEmpId() {
		return this.empId;
	}

	public void setEmpId(long empId) {
		this.empId = empId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
		this.strDob = DateUtils.toDate(dob,true);
	}

	@Column(name = "depot_id")
	public Integer getDepotId() {
		return this.depotId;
	}

	public void setDepotId(Integer depotId) {
		this.depotId = depotId;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "advance", precision = 22, scale = 0)
	public Double getAdvance() {
		return this.advance;
	}

	public void setAdvance(Double advance) {
		this.advance = advance;
	}

	@Column(name = "salary", precision = 22, scale = 0)
	public Double getSalary() {
		return this.salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}

	@Column(name = "incentive", precision = 22, scale = 0)
	public Double getIncentive() {
		return this.incentive;
	}

	public void setIncentive(Double incentive) {
		this.incentive = incentive;
	}

	@Column(name = "mobile_no", length = 15)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "address1", length = 100)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 100)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "city", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "eamil", length = 100)
	public String getEamil() {
		return this.eamil;
	}

	public void setEamil(String eamil) {
		this.eamil = eamil;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the strDob
	 */
	@Transient
	public String getStrDob() {
		return strDob;
	}

	/**
	 * @param strDob the strDob to set
	 */
	public void setStrDob(String strDob) {
		this.strDob = strDob;
		this.dob=DateUtils.toDate(strDob,true);
	}

	/**
	 * @return the editMode
	 */
	@Transient
	public boolean isEditMode() {
		return editMode;
	}

	/**
	 * @param editMode the editMode to set
	 */
	public void setEditMode(boolean editMode) {
		this.editMode = editMode;
	}
	@Column(name = "jobopencount")
	public Integer getJobOpenCount() {
		return jobOpenCount;
	}

	public void setJobOpenCount(Integer jobOpenCount) {
		this.jobOpenCount = jobOpenCount;
	}

	
}
