package com.studio.domain;
// Generated Apr 4, 2019 5:29:32 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ItemSizeRate generated by hbm2java
 */
@Entity
@Table(name = "item_size_rate", catalog = "studio")
public class ItemSizeRate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int itemId;
	private int sizeId;
	private int rateId;
	private Double amount;
	private Integer productId;
	private String itemName;
	private String sizeName;
	private String rateName;

	public ItemSizeRate() {
	}

	public ItemSizeRate(int itemId, int sizeId, int rateId) {
		this.itemId = itemId;
		this.sizeId = sizeId;
		this.rateId = rateId;
	}

	public ItemSizeRate(int itemId, int sizeId, int rateId, Double amount, Integer productId, String itemName,
			String sizeName, String rateName) {
		this.itemId = itemId;
		this.sizeId = sizeId;
		this.rateId = rateId;
		this.amount = amount;
		this.productId = productId;
		this.itemName = itemName;
		this.sizeName = sizeName;
		this.rateName = rateName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "item_id", nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "size_id", nullable = false)
	public int getSizeId() {
		return this.sizeId;
	}

	public void setSizeId(int sizeId) {
		this.sizeId = sizeId;
	}

	@Column(name = "rate_id", nullable = false)
	public int getRateId() {
		return this.rateId;
	}

	public void setRateId(int rateId) {
		this.rateId = rateId;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "product_id")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "item_name", length = 40)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "size_name", length = 40)
	public String getSizeName() {
		return this.sizeName;
	}

	public void setSizeName(String sizeName) {
		this.sizeName = sizeName;
	}

	@Column(name = "rate_name", length = 40)
	public String getRateName() {
		return this.rateName;
	}

	public void setRateName(String rateName) {
		this.rateName = rateName;
	}

}
