package com.studio.domain;
// Generated Mar 24, 2019 1:22:34 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JobAllocationId generated by hbm2java
 */
@Embeddable
public class JobAllocationId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long orderId;
	private int depotId;

	public JobAllocationId() {
	}

	public JobAllocationId(long orderId, int depotId) {
		this.orderId = orderId;
		this.depotId = depotId;
	}

	@Column(name = "order_id", nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "depot_id", nullable = false)
	public int getDepotId() {
		return this.depotId;
	}

	public void setDepotId(int depotId) {
		this.depotId = depotId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JobAllocationId))
			return false;
		JobAllocationId castOther = (JobAllocationId) other;

		return (this.getOrderId() == castOther.getOrderId()) && (this.getDepotId() == castOther.getDepotId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getOrderId();
		result = 37 * result + this.getDepotId();
		return result;
	}

}
