package com.studio.domain;
// Generated Mar 23, 2019 9:49:02 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JobAllocationStatus generated by hbm2java
 */
@Entity
@Table(name = "job_allocation_status", catalog = "studio")
public class JobAllocationStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long orderId;
	private int depotId;
	private int statusId;

	public JobAllocationStatus() {
	}

	public JobAllocationStatus(long orderId, int depotId, int statusId) {
		this.orderId = orderId;
		this.depotId = depotId;
		this.statusId = statusId;
	}

	@Id

	@Column(name = "order_id", unique = true, nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "depot_id", nullable = false)
	public int getDepotId() {
		return this.depotId;
	}

	public void setDepotId(int depotId) {
		this.depotId = depotId;
	}

	@Column(name = "status_id", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

}
