package com.studio.domain;
// Generated Mar 24, 2019 1:22:34 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.studio.utils.DateUtils;

/**
 * JobAllocation generated by hbm2java
 */
@Entity
@Table(name = "job_allocation", catalog = "studio")
public class JobAllocation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private JobAllocationId id;
	private long custId;
	private Date inTime;
	private Date outTime;
	private Integer statusId;
	private Date createdDate;
	private Date updatedDate;
	private String orderType;
	private String statusName;
	private String strInTime;
	private String strOutTime;
	private String orderDate;
	private String remarks;
	private String timeTaken;
	private Boolean isDespatch;
	private String deliveryMode;

	public JobAllocation() {
	}

	public JobAllocation(JobAllocationId id, long custId) {
		this.id = id;
		this.custId = custId;
	}

	public JobAllocation(JobAllocationId id, long custId, Date inTime, Date outTime, Integer statusId, Date createdDate,
			Date updatedDate) {
		this.id = id;
		this.custId = custId;
		this.inTime = inTime;
		this.outTime = outTime;
		this.statusId = statusId;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)),
			@AttributeOverride(name = "depotId", column = @Column(name = "depot_id", nullable = false)) })
	public JobAllocationId getId() {
		return this.id;
	}

	public void setId(JobAllocationId id) {
		this.id = id;
	}

	@Column(name = "cust_id", nullable = false)
	public long getCustId() {
		return this.custId;
	}

	public void setCustId(long custId) {
		this.custId = custId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "in_time", length = 19)
	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
		this.strInTime = DateUtils.toDate(inTime);
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "out_time", length = 19)
	public Date getOutTime() {
		return this.outTime;
	}

	public void setOutTime(Date outTime) {
		this.outTime = outTime;
		this.strOutTime = DateUtils.toDate(outTime);
	}

	@Column(name = "status_id")
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
		this.orderDate = DateUtils.toDate(createdDate);
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the orderType
	 */
	@Transient
	public String getOrderType() {
		return orderType;
	}

	/**
	 * @param orderType the orderType to set
	 */
	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	/**
	 * @return the statusName
	 */
	@Transient
	public String getStatusName() {
		return statusName;
	}

	/**
	 * @param statusName the statusName to set
	 */
	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	/**
	 * @return the strInTime
	 */
	@Transient
	public String getStrInTime() {
		return strInTime;
	}

	/**
	 * @param strInTime the strInTime to set
	 */
	public void setStrInTime(String strInTime) {
		this.strInTime = strInTime;
	}

	/**
	 * @return the strOutTime
	 */
	@Transient
	public String getStrOutTime() {
		return strOutTime;
	}

	/**
	 * @param strOutTime the strOutTime to set
	 */
	public void setStrOutTime(String strOutTime) {
		this.strOutTime = strOutTime;
	}

	/**
	 * @return the orderDate
	 */
	@Transient
	public String getOrderDate() {
		return orderDate;
	}

	/**
	 * @param orderDate the orderDate to set
	 */
	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}

	/**
	 * @return the remarks
	 */
	@Transient
	public String getRemarks() {
		return remarks;
	}

	/**
	 * @param remarks the remarks to set
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * @return the timeTaken
	 */
	@Transient
	public String getTimeTaken() {
		return timeTaken;
	}

	/**
	 * @param timeTaken the timeTaken to set
	 */
	public void setTimeTaken(String timeTaken) {
		this.timeTaken = timeTaken;
	}

	/**
	 * @return the isDespatch
	 */
	@Transient
	public Boolean getIsDespatch() {
		return isDespatch;
	}

	/**
	 * @param isDespatch the isDespatch to set
	 */
	public void setIsDespatch(Boolean isDespatch) {
		this.isDespatch = isDespatch;
	}

	/**
	 * @return the deliveryMode
	 */
	@Transient
	public String getDeliveryMode() {
		return deliveryMode;
	}

	/**
	 * @param deliveryMode the deliveryMode to set
	 */
	public void setDeliveryMode(String deliveryMode) {
		this.deliveryMode = deliveryMode;
	}
	
	

}
