package com.studio.domain;
// Generated Apr 12, 2019 1:41:51 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MetaDataMapping generated by hbm2java
 */
@Entity
@Table(name = "meta_data_mapping", catalog = "studio")
public class MetaDataMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String methodName;

	public MetaDataMapping() {
	}

	public MetaDataMapping(String name) {
		this.name = name;
	}

	public MetaDataMapping(String name, String methodName) {
		this.name = name;
		this.methodName = methodName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "method_name", length = 50)
	public String getMethodName() {
		return this.methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

}
