//package com.studio.domain;
//
//
//import java.util.ArrayList;
//import java.util.Date;
//import java.util.List;
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.OneToMany;
//import javax.persistence.PrimaryKeyJoinColumn;
//import javax.persistence.SecondaryTable;
//import javax.persistence.Table;
//import javax.persistence.Temporal;
//import javax.persistence.TemporalType;
//import javax.persistence.Transient;
//
//import org.springframework.util.StringUtils;
//import java.lang.annotation.Repeatable;
//
//import com.studio.utils.DateUtils;
//
///**
// * Receipt generated by hbm2java
// */
//@Entity
//@Table(name = "new_table", catalog = "studio")
//
//
//@SecondaryTable(name="new_table_2", pkJoinColumns = @PrimaryKeyJoinColumn(name = "emp_id", referencedColumnName = "id"))
//public class NewTable implements java.io.Serializable {
//private int id;
//private int emp_id;
//private String name;
//private String email;
//
//@Column(table="new_table_2")
//private String address;
//@Column(table="new_table_2")
//private String city;
//
//@Id
//@Column(name = "id", unique = true, nullable = false)
//@GeneratedValue(strategy = GenerationType.AUTO)
//public int getId() {
//	return id;
//}
//
//public void setId(int id) {
//	this.id = id;
//}
//
//@Column(name = "emp_id", unique = true, nullable = false)
//public int getEmpId() {
//	return emp_id;
//}
//
//public void setEmpId(int empid) {
//	this.emp_id = empid;
//}
//@Column(name = "name", nullable = false)
//public String getName() {
//	return name;
//}
//public void setName(String name) {
//	this.name = name;
//}
//@Column(name = "email", nullable = false)
//public String getEmail() {
//	return email;
//}
//public void setEmail(String email) {
//	this.email = email;
//}
//
//
//@Column(name="address",table="new_table_2")
//public String getAddress() {
//	return address;
//}
//
//public void setAddress(String address) {
//	this.address = address;
//}
//@Column(name="city",table="new_table_2")
//public String getCity() {
//	return city;
//}
//
//public void setCity(String city) {
//	this.city = city;
//}
//
//public NewTable() {
//	super();
//	// TODO Auto-generated constructor stub
//}
//
//
//
//public NewTable(int id,int empid, String name, String email,String address, String city) {
//	super();
//	this.id = id;
//	this.emp_id = empid;
//	this.name = name;
//	this.email = email;
//	this.address =address;
//	this.city = city;
//}
//@Override
//public String toString() {
//	return "NewTable [id=" + id + ",empid=" + emp_id + ", name=" + name + ", email=" + email + ", address=" + address + ", city=" + city + "]";
//}
//}
