package com.studio.domain;
// Generated Mar 20, 2019 11:51:48 PM by Hibernate Tools 5.2.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.studio.utils.DateUtils;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "studio")
public class Order implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long orderId;
	private long custId;
	private Date orderDate;
	private String orderType;
	private String agentName;
	private String custName;
	private Integer custType;
	private Double creditBalance;
	// for checklist printing 
	private Double balancePayable;
	//
	private String gstNo;
	private Date dueDate;
	private String wrapperName;
	private String deliveryTypeId;
	private String remarks;
	private Date createdDate;
	private Date updatedDate;
	//private Date cancelDate;
	private List<Product> products = new ArrayList<Product>();
	
	private List<OrderTrxnDetail> orderTrxnDetails= new ArrayList<OrderTrxnDetail>();
	private String strOrderDate;
	private String strDueDate;
	private String custAddr1;
	private String custAddr2;
	private List<JobAllocation> jobAllocations= new ArrayList<JobAllocation>();
	private Integer rateType;
	private Integer smsFlag;
	private String mobileNo;
	private Integer status;
	private boolean editMode;
	private boolean cancelMode;
	private boolean enablePayment;
	private String strOrderId;
	private String deliveryType;
	private String email;
 /*	private int days;*/
	private int noOfSheet;
	private int noOfCopy;
	private String billBy;
	private long prodId;
	private long prodItemId;
	private int totitem;
	public Order() {
	}

	public Order(long orderId, long custId) {
		this.orderId = orderId;
	}

	public Order(long orderId, Long custId, Date orderDate, String orderType, String agentName, String custName,String email,
			Integer custType, Double creditBalance, Double balancePayable,String gstNo, Date dueDate, String wrapperName,
			String deliveryTypeId, String remarks, Date createdDate, Date updatedDate, Integer status, String custAddr1,
			String custAddr2,  Integer rateType,Integer smsFlag,Integer noOfSheet,int noOfCopy, String billBy, int totitem) {
		// newly added 
				//System.out.println(">>>>>>>>>"+ creditBalance);		
		this.orderId = orderId;
		this.custId = custId;
		this.orderDate = orderDate;
		this.orderType = orderType;
		this.agentName = agentName;
		this.custName = custName;
		this.custType = custType;
		this.creditBalance = creditBalance;
		this.balancePayable=balancePayable;
		this.gstNo = gstNo;
		this.dueDate = dueDate;
		this.wrapperName = wrapperName;
		this.deliveryTypeId = deliveryTypeId;
		this.remarks = remarks;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.smsFlag = smsFlag;
		this.status = status;
		this.custAddr1 = custAddr1;
		this.custAddr2 = custAddr2;
		this.rateType = rateType;
		this.email=email;
		this.noOfSheet=noOfSheet;
		this.noOfCopy=noOfCopy;
		this.billBy=billBy;
		this.setTotitem(totitem);
		/*this.noOfSheet=noOfSheet;*/
	}

	
	@Id

	@Column(name = "order_id", unique = true, nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
//		this.strOrderId = String.valueOf(orderId);
	}

	@Column(name = "cust_id")
	public long getCustId() {
		return this.custId;
	}

	public void setCustId(long custId) {
		this.custId = custId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
		this.strOrderDate = DateUtils.toDate(orderDate);
	}

	@Column(name = "order_type", length = 20)
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Column(name = "agent_name", length = 40)
	public String getAgentName() {
		return this.agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}
	
	@Column(name = "cust_name", length = 100)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "cust_type")
	public Integer getCustType() {
		return this.custType;
	}

	public void setCustType(Integer custType) {
		this.custType = custType;
	}
	
	@Column(name = "sms_flag")
	public Integer getSmsFlag() {
		return this.smsFlag;
	}

	public void setSmsFlag(Integer smsFlag) {
		this.smsFlag = smsFlag;
	}
	@Column(name = "creditBalance", precision = 22, scale = 0)
	public Double getCreditBalance() {
		return this.creditBalance;
	}

	public void setCreditBalance(Double creditBalance) {
		this.creditBalance = creditBalance;
	}

	@Column(name = "gst_no", length = 20)
	public String getGstNo() {
		return this.gstNo;
	}

	public void setGstNo(String gstNo) {
		this.gstNo = gstNo;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
		this.strDueDate=DateUtils.toDate(dueDate);
	}

	@Column(name = "wrapper_name", length = 100)
	public String getWrapperName() {
		return this.wrapperName;
	}

	public void setWrapperName(String wrapperName) {
		this.wrapperName = wrapperName;
	}

	@Column(name = "delivery_type_id", length = 20)
	public String getDeliveryTypeId() {
		return this.deliveryTypeId;
	}

	public void setDeliveryTypeId(String deliveryTypeId) {
		this.deliveryTypeId = deliveryTypeId;
	}

	@Column(name = "remarks", length = 200)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	/*@Temporal(TemporalType.DATE)
	@Column(name = "cancel_date", length = 10)
	public Date getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(Date cancelDate) {
		this.cancelDate = cancelDate;
	}*/

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * @return the products
	 */
	@Transient
	public List<Product> getProducts() {
		return products;
	}

	public void setProducts(List<Product> products) {
		this.products = products;
	}
	
	// @param products the products to set
	
	

	/*@Transient
	public List<ProductTemp> getProductsTemp() {
		return productstemp;
	}
	public void setProductsTemp(List<ProductTemp> productstemp) {
		this.productstemp = productstemp;
	}
	*/
	
	/**
	 * @return the orderTrxnDetails
	 */
	
	@Transient
	public List<OrderTrxnDetail> getOrderTrxnDetails() {
		return orderTrxnDetails;
	}

	/**
	 * @param orderTrxnDetails the orderTrxnDetails to set
	 */
	public void setOrderTrxnDetails(List<OrderTrxnDetail> orderTrxnDetails) {
		this.orderTrxnDetails = orderTrxnDetails;
	}

	/**
	 * @return the strOrderDate
	 */
	@Transient
	public String getStrOrderDate() {
		return strOrderDate;
	}

	/**
	 * @param strOrderDate the strOrderDate to set
	 */
	public void setStrOrderDate(String strOrderDate) {
		this.strOrderDate = strOrderDate;
		if(strOrderDate!=null && strOrderDate.contains(":"))
			this.orderDate=DateUtils.toDate(strOrderDate);
		else if(strOrderDate != null)
			this.orderDate=DateUtils.toDate(strOrderDate,true);
	}

	/**
	 * @return the strDueDate
	 */
	@Transient
	public String getStrDueDate() {
		return strDueDate;
	}

	/**
	 * @param strDueDate the strDueDate to set
	 */
	public void setStrDueDate(String strDueDate) {
		this.strDueDate = strDueDate;
		if(strDueDate!=null && strDueDate.contains(":"))
			this.dueDate=DateUtils.toDate(strDueDate);
		else if(strDueDate!=null)
			this.dueDate=DateUtils.toDate(strDueDate,true);
	}

	@Column(name = "cust_addr1", length = 50)
	public String getCustAddr1() {
		return this.custAddr1;
	}

	public void setCustAddr1(String custAddr1) {
		this.custAddr1 = custAddr1;
	}

	@Column(name = "cust_addr2", length = 50)
	public String getCustAddr2() {
		return this.custAddr2;
	}

	public void setCustAddr2(String custAddr2) {
		this.custAddr2 = custAddr2;
	}
	@Column(name = "billby", length=45)
	public String getBillBy() {
		return billBy;
	}

	public void setBillBy(String billBy) {
		this.billBy = billBy;
	}
	

	/**
	 * @return the jobAllocations
	 */
	@Transient
	public List<JobAllocation> getJobAllocations() {
		return jobAllocations;
	}

	/**
	 * @param jobAllocations the jobAllocations to set
	 */
	public void setJobAllocations(List<JobAllocation> jobAllocations) {
		this.jobAllocations = jobAllocations;
	}

	@Column(name = "rateType")
	public Integer getRateType() {
		return this.rateType;
	}

	public void setRateType(Integer rateType) {
		this.rateType = rateType;
	}

	/**
	 * @return the mobileNo
	 */
	@Transient
	public String getMobileNo() {
		return mobileNo;
	}

	/**
	 * @param mobileNo the mobileNo to set
	 */
	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	/**
	 * @return the editMode
	 */
	@Transient
	public boolean isEditMode() {
		return editMode;
	}

	/**
	 * @param editMode the editMode to set
	 */
	public void setEditMode(boolean editMode) {
		this.editMode = editMode;
	}

	/**
	 * @return the cancelMode
	 */
	@Transient
	public boolean isCancelMode() {
		return cancelMode;
	}

	/**
	 * @param cancelMode the cancelMode to set
	 */
	public void setCancelMode(boolean cancelMode) {
		this.cancelMode = cancelMode;
	}

	/**
	 * @return the strOrderId
	 */
	@Transient
	public String getStrOrderId() {
		return strOrderId;
	}

	/**
	 * @param strOrderId the strOrderId to set
	 */
	public void setStrOrderId(String strOrderId) {
		this.strOrderId = strOrderId;
		/*if(!StringUtils.isEmpty(strOrderId))
			this.orderId=Long.valueOf(strOrderId);
		else
			this.orderId=0;*/
	}
	/*@Transient
	public int getDays() {
		return days;
	}
	@Transient
	public void setDays(int days) {
		this.days = days;
	}*/
	@Transient
	public String getDeliveryType() {
		return deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}
	@Transient
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	@Transient
	public int getNoOfSheet() {
		return noOfSheet;
	}

	public void setNoOfSheet(int noOfSheet) {
		this.noOfSheet = noOfSheet;
	}
	@Transient
	public int getNoOfCopy() {
		return noOfCopy;
	}

	public void setNoOfCopy(int noOfCopy) {
		this.noOfCopy = noOfCopy;
	}
	@Transient
	public int getTotitem() {
		return totitem;
	}

	public void setTotitem(int totitem) {
		this.totitem = totitem;
	}
	@Transient
	public Double getBalancePayable() {
		return balancePayable;
	}

	public void setBalancePayable(Double balancePayable) {
		this.balancePayable = balancePayable;
	}
	@Transient
	public long getProdId() {
		return prodId;
	}

	public void setProdId(long prodId) {
		this.prodId = prodId;
	}
	@Transient
	public long getProdItemId() {
		return prodItemId;
	}

	public void setProdItemId(long prodItemId) {
		this.prodItemId = prodItemId;
	}
	@Transient
	public boolean isEnablePayment() {
		return enablePayment;
	}

	public void setEnablePayment(boolean enablePayment) {
		this.enablePayment = enablePayment;
	}

 
}
