package com.studio.domain;
// Generated Mar 20, 2019 11:51:48 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.studio.utils.DateUtils;

/**
 * OrderTrxnDetail generated by hbm2java
 */
@Entity
@Table(name = "order_trxn_detail", catalog = "studio")
public class OrderTrxnDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long trxnId;
	private long orderId;
	private Double total;
	private Double discount;
	private Double subTotal;
	private Double cgst;
	private Double sgst;
	private Double igst;
	private Double delvCharge;
	private Double netAmount;
	private Double advance;
	private Double balance;
	private String pymtType;
	private String chequeNo;
	private Date chequeDate;
	private String bankName;
	private Double chequeAmount;
	private Date createdDate;
	private Date updatedDate;
	private String strChequeDate;

	public OrderTrxnDetail() {
	}

	public OrderTrxnDetail(long trxnId, long orderId) {
		this.trxnId = trxnId;
		this.orderId = orderId;
	}
	
	public OrderTrxnDetail(Date createdDate, Double netAmount, Double advance,long orderId) {
		this.createdDate = createdDate;
		this.netAmount = netAmount;
		this.advance = advance;
		this.orderId=orderId;
	}

	public OrderTrxnDetail(long trxnId, long orderId, Double total, Double discount, Double subTotal, Double cgst,
			Double sgst, Double igst,Double delvCharge, Double netAmount, Double advance, Double balance, String pymtType,
			String chequeNo, Date chequeDate, String bankName, Double chequeAmount, Date createdDate,
			Date updatedDate) {
		this.trxnId = trxnId;
		this.orderId = orderId;
		this.total = total;
		this.discount = discount;
		this.subTotal = subTotal;
		this.cgst = cgst;
		this.sgst = sgst;
		this.igst=igst;
		this.delvCharge = delvCharge;
		this.netAmount = netAmount;
		this.advance = advance;
		this.balance = balance;
		this.pymtType = pymtType;
		this.chequeNo = chequeNo;
		this.chequeDate = chequeDate;
		this.bankName = bankName;
		this.chequeAmount = chequeAmount;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "trxn_id", unique = true, nullable = false)
	public long getTrxnId() {
		return this.trxnId;
	}

	public void setTrxnId(long trxnId) {
		this.trxnId = trxnId;
	}

	@Column(name = "order_id", nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "total", precision = 22, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Column(name = "discount", precision = 22, scale = 0)
	public Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	@Column(name = "sub_total", precision = 22, scale = 0)
	public Double getSubTotal() {
		return this.subTotal;
	}

	public void setSubTotal(Double subTotal) {
		this.subTotal = subTotal;
	}

	@Column(name = "cgst", precision = 22, scale = 0)
	public Double getCgst() {
		return this.cgst;
	}

	public void setCgst(Double cgst) {
		this.cgst = cgst;
	}

	@Column(name = "sgst", precision = 22, scale = 0)
	public Double getSgst() {
		return this.sgst;
	}

	public void setSgst(Double sgst) {
		this.sgst = sgst;
	}
	@Column(name = "igst", precision = 22, scale = 0)
	public Double getIgst() {
		return igst;
	}

	public void setIgst(Double igst) {
		this.igst = igst;
	}
	
	
	@Column(name = "delv_charge", precision = 22, scale = 0)
	public Double getDelvCharge() {
		return this.delvCharge;
	}

	public void setDelvCharge(Double delvCharge) {
		this.delvCharge = delvCharge;
	}

	@Column(name = "net_amount", precision = 22, scale = 0)
	public Double getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(Double netAmount) {
		this.netAmount = netAmount;
	}

	@Column(name = "advance", precision = 22, scale = 0)
	public Double getAdvance() {
		return this.advance;
	}

	public void setAdvance(Double advance) {
		this.advance = advance;
	}

	@Column(name = "balance", precision = 22, scale = 0)
	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

	@Column(name = "pymt_type", length = 20)
	public String getPymtType() {
		return this.pymtType;
	}

	public void setPymtType(String pymtType) {
		this.pymtType = pymtType;
	}

	@Column(name = "cheque_no", length = 30)
	public String getChequeNo() {
		return this.chequeNo;
	}

	public void setChequeNo(String chequeNo) {
		this.chequeNo = chequeNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cheque_date", length = 10)
	public Date getChequeDate() {
		return this.chequeDate;
	}

	public void setChequeDate(Date chequeDate) {
		this.chequeDate = chequeDate;
	}

	@Column(name = "bank_name", length = 40)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "cheque_amount", precision = 22, scale = 0)
	public Double getChequeAmount() {
		return this.chequeAmount;
	}

	public void setChequeAmount(Double chequeAmount) {
		this.chequeAmount = chequeAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
		this.strChequeDate = DateUtils.toDate(updatedDate);
	}

	/**
	 * @return the strChequeDate
	 */
	@Transient
	public String getStrChequeDate() {
		return strChequeDate;
	}

	/**
	 * @param strChequeDate the strChequeDate to set
	 */
	public void setStrChequeDate(String strChequeDate) {
		this.strChequeDate = strChequeDate;
		this.chequeDate = DateUtils.toDate(strChequeDate);
	}
	
	
	
	

}
