package com.studio.domain;
// Generated Mar 21, 2019 11:56:35 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "studio")
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long productId;
	private long productTypeId;
	private long orderId;
	private Integer noOfCopy;
	private Integer noOfSheet;
	private Integer size;
	private Date createdDate;
	private Date updatedDate;
	private List<ProductItem> productItems = new ArrayList<ProductItem>();
	private String name;
	private String sizeName;
	private long prodno;
	public Product() {
	}

	public Product(long productTypeId, long orderId) {
		this.productTypeId = productTypeId;
		this.orderId = orderId;
	}
	
	public Product(Date  createdDate, Integer noOfSheet) {
		this.createdDate = createdDate;
		this.noOfSheet = noOfSheet;
	}
	

	public Product(long productTypeId, long orderId, Integer noOfCopy, Integer noOfSheet, Integer size,
			Date createdDate, Date updatedDate) {
		this.productTypeId = productTypeId;
		this.orderId = orderId;
		this.noOfCopy = noOfCopy;
		this.noOfSheet = noOfSheet;
		this.size = size;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_id", unique = true, nullable = false)
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "product_type_id", nullable = false)
	public long getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(long productTypeId) {
		this.productTypeId = productTypeId;
	}

	@Column(name = "order_id", nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "no_of_copy")
	public Integer getNoOfCopy() {
		return this.noOfCopy;
	}

	public void setNoOfCopy(Integer noOfCopy) {
		this.noOfCopy = noOfCopy;
	}

	@Column(name = "no_of_sheet")
	public Integer getNoOfSheet() {
		return this.noOfSheet;
	}

	public void setNoOfSheet(Integer noOfSheet) {
		this.noOfSheet = noOfSheet;
	}

	@Column(name = "size")
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the productItems
	 */
	@Transient
	public List<ProductItem> getProductItems() {
		return productItems;
	}

	/**
	 * @param productItems the productItems to set
	 */
	public void setProductItems(List<ProductItem> productItems) {
		this.productItems = productItems;
	}

	/**
	 * @return the name
	 */
	@Transient
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the sizeName
	 */
	@Transient
	public String getSizeName() {
		return sizeName;
	}

	/**
	 * @param sizeName the sizeName to set
	 */
	public void setSizeName(String sizeName) {
		this.sizeName = sizeName;
	}
	
	@Transient
	public long getProdNo() {
		return prodno;
	}

	/**
	 * @param prodSize the prodSize to set
	 */
	public void setProdNo(long prodNo) {
		this.prodno = prodNo;
	}
	
	
}
