package com.studio.domain;
// Generated Apr 10, 2019 12:02:25 AM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.studio.utils.DateUtils;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name = "purchase", catalog = "studio")
public class Purchase implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String invoiceNumber;
	private Date invoiceDate;
	private Long supId;
	private String gstNo;
	private Double sgstAmount;
	private Double cgstAmount;
	private Double igstAmount;
	private Double invoiceAmount;
	private Double discount;
	private Double roundOff;
	private Double netPayable;
	private Double amountPaid;
	private Double balancePayable;
	private Integer paymentId;
	private String chequeNo;
	private Date chequeDate;
	private String bankName;
	private Date createdDate;
	private Date updatedDate;
	private List<PurchasePayment> purchasePayments = new ArrayList<PurchasePayment>();
	private String strInvoiceDate;
	private String strChequeDate;
	private Double advance;
	private String strGoodsReceivedDate;
	private Date goodsReceivedDate;

	public Purchase() {
	}

	public Purchase(Date createdDate,Double netPayable  ) {
		this.createdDate = createdDate;
		this.netPayable = netPayable;
	}
	
	public Purchase(String invoiceNumber, Date invoiceDate, Long supId, String gstNo, Double sgstAmount,
			Double cgstAmount, Double igstAmount, Double invoiceAmount, Double discount, Double roundOff,
			Double netPayable, Double amountPaid, Double balancePayable, Integer paymentId, String chequeNo,
			Date chequeDate, String bankName, Date createdDate, Date updatedDate, Date goodsReceivedDate,List<PurchasePayment> purchasePayments) {
		this.invoiceNumber = invoiceNumber;
		this.invoiceDate = invoiceDate;
		this.supId = supId;
		this.gstNo = gstNo;
		this.sgstAmount = sgstAmount;
		this.cgstAmount = cgstAmount;
		this.igstAmount = igstAmount;
		this.invoiceAmount = invoiceAmount;
		this.discount = discount;
		this.roundOff = roundOff;
		this.netPayable = netPayable;
		this.amountPaid = amountPaid;
		this.balancePayable = balancePayable;
		this.paymentId = paymentId;
		this.chequeNo = chequeNo;
		this.chequeDate = chequeDate;
		this.bankName = bankName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.goodsReceivedDate = goodsReceivedDate;
		this.purchasePayments = purchasePayments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "invoice_number", length = 50)
	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "invoice_date", length = 10)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
		this.strInvoiceDate = DateUtils.toDate(invoiceDate,true);
	}

	@Column(name = "sup_id")
	public Long getSupId() {
		return this.supId;
	}

	public void setSupId(Long supId) {
		this.supId = supId;
	}

	@Column(name = "gst_no", length = 20)
	public String getGstNo() {
		return this.gstNo;
	}

	public void setGstNo(String gstNo) {
		this.gstNo = gstNo;
	}

	@Column(name = "sgst_amount", precision = 22, scale = 0)
	public Double getSgstAmount() {
		return this.sgstAmount;
	}

	public void setSgstAmount(Double sgstAmount) {
		this.sgstAmount = sgstAmount;
	}

	@Column(name = "cgst_amount", precision = 22, scale = 0)
	public Double getCgstAmount() {
		return this.cgstAmount;
	}

	public void setCgstAmount(Double cgstAmount) {
		this.cgstAmount = cgstAmount;
	}

	@Column(name = "igst_amount", precision = 22, scale = 0)
	public Double getIgstAmount() {
		return this.igstAmount;
	}

	public void setIgstAmount(Double igstAmount) {
		this.igstAmount = igstAmount;
	}

	@Column(name = "invoice_amount", precision = 22, scale = 0)
	public Double getInvoiceAmount() {
		return this.invoiceAmount;
	}

	public void setInvoiceAmount(Double invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	@Column(name = "discount", precision = 22, scale = 0)
	public Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	@Column(name = "round_off", precision = 22, scale = 0)
	public Double getRoundOff() {
		return this.roundOff;
	}

	public void setRoundOff(Double roundOff) {
		this.roundOff = roundOff;
	}

	@Column(name = "net_payable", precision = 22, scale = 0)
	public Double getNetPayable() {
		return this.netPayable;
	}

	public void setNetPayable(Double netPayable) {
		this.netPayable = netPayable;
	}

	@Column(name = "amount_paid", precision = 22, scale = 0)
	public Double getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(Double amountPaid) {
		this.amountPaid = amountPaid;
	}

	@Column(name = "balance_payable", precision = 22, scale = 0)
	public Double getBalancePayable() {
		return this.balancePayable;
	}

	public void setBalancePayable(Double balancePayable) {
		this.balancePayable = balancePayable;
	}

	@Column(name = "payment_id")
	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "cheque_no", length = 50)
	public String getChequeNo() {
		return this.chequeNo;
	}

	public void setChequeNo(String chequeNo) {
		this.chequeNo = chequeNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cheque_date", length = 10)
	public Date getChequeDate() {
		return this.chequeDate;
	}

	public void setChequeDate(Date chequeDate) {
		this.chequeDate = chequeDate;
		this.strChequeDate = DateUtils.toDate(chequeDate);
	}

	@Column(name = "bank_name", length = 100)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "purchase")
	public List<PurchasePayment> getPurchasePayments() {
		return this.purchasePayments;
	}

	public void setPurchasePayments(List<PurchasePayment> purchasePayments) {
		this.purchasePayments = purchasePayments;
	}

	/**
	 * @return the strInvoiceDate
	 */
	@Transient
	public String getStrInvoiceDate() {
		return strInvoiceDate;
	}

	/**
	 * @param strInvoiceDate the strInvoiceDate to set
	 */
	public void setStrInvoiceDate(String strInvoiceDate) {
		this.strInvoiceDate = strInvoiceDate;
		this.invoiceDate = DateUtils.toDate(strInvoiceDate,true);
	}

	/**
	 * @return the strChequeDate
	 */
	@Transient
	public String getStrChequeDate() {
		return strChequeDate;
	}

	/**
	 * @param strChequeDate the strChequeDate to set
	 */
	public void setStrChequeDate(String strChequeDate) {
		this.strChequeDate = strChequeDate;
		this.chequeDate=DateUtils.toDate(strChequeDate,true);
	}

	/**
	 * @return the advance
	 */
	@Transient
	public Double getAdvance() {
		return advance;
	}

	/**
	 * @param advance the advance to set
	 */
	public void setAdvance(Double advance) {
		this.advance = advance;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "goods_received_date", length = 10)
	public Date getGoodsReceivedDate() {
		return this.goodsReceivedDate;
	}

	public void setGoodsReceivedDate(Date goodsReceivedDate) {
		this.goodsReceivedDate = goodsReceivedDate;
	}

	/**
	 * @return the strGoodsReceivedDate
	 */
	@Transient
	public String getStrGoodsReceivedDate() {
		return strGoodsReceivedDate;
	}

	/**
	 * @param strGoodsReceivedDate the strGoodsReceivedDate to set
	 */
	public void setStrGoodsReceivedDate(String strGoodsReceivedDate) {
		this.strGoodsReceivedDate = strGoodsReceivedDate;
		this.goodsReceivedDate = DateUtils.toDate(strGoodsReceivedDate,true);
	}

	
}
