package com.studio.domain;
// Generated Apr 10, 2019 12:02:25 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchasePayment generated by hbm2java
 */
@Entity
@Table(name = "purchase_payment", catalog = "studio")
public class PurchasePayment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Purchase purchase;
	private int purchaseTypeId;
	private String batchNo;
	private String gstRate;
	private Integer qty;
	private Double rate;
	private Double amount;
	private Date createdDate;
	private Date updatedDate;

	public PurchasePayment() {
	}

	public PurchasePayment(Purchase purchase, int purchaseTypeId) {
		this.purchase = purchase;
		this.purchaseTypeId = purchaseTypeId;
	}

	public PurchasePayment(Purchase purchase, int purchaseTypeId, String batchNo, String gstRate, Integer qty,
			Double rate, Double amount, Date createdDate, Date updatedDate) {
		this.purchase = purchase;
		this.purchaseTypeId = purchaseTypeId;
		this.batchNo = batchNo;
		this.gstRate = gstRate;
		this.qty = qty;
		this.rate = rate;
		this.amount = amount;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pur_id", nullable = false)
	public Purchase getPurchase() {
		return this.purchase;
	}

	public void setPurchase(Purchase purchase) {
		this.purchase = purchase;
	}

	@Column(name = "purchase_type_id", nullable = false)
	public int getPurchaseTypeId() {
		return this.purchaseTypeId;
	}

	public void setPurchaseTypeId(int purchaseTypeId) {
		this.purchaseTypeId = purchaseTypeId;
	}

	@Column(name = "batch_no", length = 50)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "gst_rate", length = 10)
	public String getGstRate() {
		return this.gstRate;
	}

	public void setGstRate(String gstRate) {
		this.gstRate = gstRate;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "rate", precision = 22, scale = 0)
	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
