package com.studio.domain;
// Generated Apr 9, 2019 5:44:15 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "studio")
public class Supplier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long supId;
	private String name;
	private Double creditBalance=0.0;
	private String address1;
	private String address2;
	private Integer stateId;
	private String pin;
	private String phoneNo;
	private String mobileNo;
	private String eamil;
	private Date createdDate;
	private Date updatedDate;
	private boolean editMode;
	private String gstNo="99999";

	public Supplier() {
	}

	public Supplier(long supId, String name) {
		this.supId = supId;
		this.name = name;
	}

	public Supplier(long supId, String name, Double creditBalance, String address1, String address2, Integer stateId,
			String pin, String phoneNo, String mobileNo, String eamil, Date createdDate, Date updatedDate) {
		this.supId = supId;
		this.name = name;
		this.creditBalance = creditBalance;
		this.address1 = address1;
		this.address2 = address2;
		this.stateId = stateId;
		this.pin = pin;
		this.phoneNo = phoneNo;
		this.mobileNo = mobileNo;
		this.eamil = eamil;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "sup_id", unique = true, nullable = false)
	public long getSupId() {
		return this.supId;
	}

	public void setSupId(long supId) {
		this.supId = supId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "credit_balance", precision = 22, scale = 0)
	public Double getCreditBalance() {
		return this.creditBalance;
	}

	public void setCreditBalance(Double creditBalance) {
		this.creditBalance = creditBalance;
	}

	@Column(name = "address1", length = 100)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 100)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "state_id")
	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	@Column(name = "pin", length = 10)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "phone_no", length = 15)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "mobile_no", length = 15)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "eamil", length = 100)
	public String getEamil() {
		return this.eamil;
	}

	public void setEamil(String eamil) {
		this.eamil = eamil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the editMode
	 */
	@Transient
	public boolean isEditMode() {
		return editMode;
	}

	/**
	 * @param editMode the editMode to set
	 */
	public void setEditMode(boolean editMode) {
		this.editMode = editMode;
	}

	/**
	 * @return the gstNo
	 */
	@Column(name = "gst_no", length = 20)
	public String getGstNo() {
		return this.gstNo;
	}

	public void setGstNo(String gstNo) {
		this.gstNo = gstNo;
	}
	
	

}
