package com.studio.domain;
// Generated Apr 11, 2019 4:17:13 AM by Hibernate Tools 5.2.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.springframework.util.StringUtils;

import com.studio.utils.DateUtils;

/**
 * Voucher generated by hbm2java
 */
@Entity
@Table(name = "voucher", catalog = "studio")
public class Voucher implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long voucherId;
	private Date voucherDate;
	private int paymentId;
	private int expenseId;
	private double payAmount;
	private double balanceAmount;
	private String naration;
	private String chequeNo;
	private Date chequeDate;
	private String bankName;
	private Date createdDate;
	private Date updatedDate;
	private List<VoucherPayment> voucherPayments = new ArrayList<VoucherPayment>();
	private String strVoucherDate;
	private Double creditBalance;
	private String strChequeDate;
	private String strPayAmount;
	private String strPaymentId;
	private String preparedBy;
	
		

	public Voucher() {
	}

	public Voucher(long voucherId, int paymentId, int expenseId, double payAmount, double balanceAmount) {
		this.voucherId = voucherId; 
		this.paymentId = paymentId;
		this.expenseId = expenseId;
		this.payAmount = payAmount;
		this.balanceAmount = balanceAmount;
	}
	
	  public Voucher( Date voucherDate, double payAmount)
	  {
	    this.voucherDate = voucherDate;
	    this.payAmount = payAmount;
	  }
	

	public Voucher( long voucherId, Date voucherDate, double payAmount) {
		this.voucherDate = voucherDate;
		this.payAmount = payAmount;
		this.voucherId=voucherId;
	}
	public Voucher(long voucherId, Date voucherDate, int paymentId, int expenseId, double payAmount,
			double balanceAmount, String naration, String chequeNo, Date chequeDate, String bankName, Date createdDate,
			Date updatedDate, String preparedBy) {
		this.voucherId = voucherId;
		this.voucherDate = voucherDate;
		this.paymentId = paymentId;
		this.expenseId = expenseId;
		this.payAmount = payAmount;
		this.balanceAmount = balanceAmount;
		this.naration = naration;
		this.chequeNo = chequeNo;
		this.chequeDate = chequeDate;
		this.bankName = bankName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.preparedBy=preparedBy;
	}

	@Id

	@Column(name = "voucher_id", unique = true, nullable = false)
	public long getVoucherId() {
		return this.voucherId;
	}

	public void setVoucherId(long voucherId) {
		this.voucherId = voucherId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "voucher_date", length = 10)
	public Date getVoucherDate() {
		return this.voucherDate;
	}

	public void setVoucherDate(Date voucherDate) {
		this.voucherDate = voucherDate;
		this.strVoucherDate = DateUtils.toDate(voucherDate);
	}

	@Column(name = "payment_id", nullable = false)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "expense_id", nullable = false)
	public int getExpenseId() {
		return this.expenseId;
	}

	public void setExpenseId(int expenseId) {
		this.expenseId = expenseId;
	}

	@Column(name = "pay_amount", nullable = false, precision = 22, scale = 0)
	public double getPayAmount() {
		return this.payAmount;
	}

	public void setPayAmount(double payAmount) {
		this.payAmount = payAmount;
		this.strPayAmount = String.valueOf(payAmount);
	}

	@Column(name = "balance_amount", nullable = false, precision = 22, scale = 0)
	public double getBalanceAmount() {
		return this.balanceAmount;
	}

	public void setBalanceAmount(double balanceAmount) {
		this.balanceAmount = balanceAmount;
	}

	@Column(name = "naration", length = 500)
	public String getNaration() {
		return this.naration;
	}

	public void setNaration(String naration) {
		this.naration = naration;
	}

	@Column(name = "cheque_no", length = 50)
	public String getChequeNo() {
		return this.chequeNo;
	}

	public void setChequeNo(String chequeNo) {
		this.chequeNo = chequeNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cheque_date", length = 10)
	public Date getChequeDate() {
		return this.chequeDate;
	}

	public void setChequeDate(Date chequeDate) {
		this.chequeDate = chequeDate;
		this.strChequeDate = DateUtils.toDate(chequeDate,true);
	}

	@Column(name = "bank_name", length = 100)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the voucherPayments
	 */
	@Transient
	public List<VoucherPayment> getVoucherPayments() {
		return voucherPayments;
	}

	/**
	 * @param voucherPayments the voucherPayments to set
	 */
	public void setVoucherPayments(List<VoucherPayment> voucherPayments) {
		this.voucherPayments = voucherPayments;
	}

	/**
	 * @return the strVoucherDate
	 */
	@Transient
	public String getStrVoucherDate() {
		return strVoucherDate;
	}

	/**
	 * @param strVoucherDate the strVoucherDate to set
	 */
	public void setStrVoucherDate(String strVoucherDate) {
		this.strVoucherDate = strVoucherDate;
		if(strVoucherDate!=null && strVoucherDate.contains(":"))
			this.voucherDate = DateUtils.toDate(strVoucherDate);
		else if(strVoucherDate!=null)
			this.voucherDate = DateUtils.toDate(strVoucherDate,true);
	}

	/**
	 * @return the creditBalance
	 */
	@Transient
	public Double getCreditBalance() {
		return creditBalance;
	}

	/**
	 * @param creditBalance the creditBalance to set
	 */
	public void setCreditBalance(Double creditBalance) {
		this.creditBalance = creditBalance;
	}

	/**
	 * @return the strChequeDate
	 */
	@Transient
	public String getStrChequeDate() {
		return strChequeDate;
	}

	/**
	 * @param strChequeDate the strChequeDate to set
	 */
	public void setStrChequeDate(String strChequeDate) {
		this.strChequeDate = strChequeDate;
		this.chequeDate = DateUtils.toDate(strChequeDate,true);
	}

	/**
	 * @return the strPayAmount
	 */
	@Transient
	public String getStrPayAmount() {
		return strPayAmount;
	}

	/**
	 * @param strPayAmount the strPayAmount to set
	 */
	public void setStrPayAmount(String strPayAmount) {
		this.strPayAmount = strPayAmount;
		if(!StringUtils.isEmpty(strPayAmount))
			this.payAmount = Double.valueOf(strPayAmount);
	}

	/**
	 * @return the strPaymentId
	 */
	@Transient
	public String getStrPaymentId() {
		return strPaymentId;
	}

	/**
	 * @param strPaymentId the strPaymentId to set
	 */
	public void setStrPaymentId(String strPaymentId) {
		this.strPaymentId = strPaymentId;
		if(!StringUtils.isEmpty(strPaymentId))
			setPaymentId(Integer.valueOf(strPaymentId));
	}

	public String getPreparedBy() {
		return preparedBy;
	}

	public void setPreparedBy(String preparedBy) {
		this.preparedBy = preparedBy;
	}

	

}
