package com.studio.domain;
// Generated Apr 11, 2019 4:17:13 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * VoucherPayment generated by hbm2java
 */
@Entity
@Table(name = "voucher_payment", catalog = "studio")
public class VoucherPayment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private long voucherId;
	private String refTypeId;
	private String refNo;
	private Double netAmount;
	private Double paidAmount;
	private Date createdDate;
	private Date updatedDate;
	private Double balance;
	private String gstNo;

	public VoucherPayment() {
	}

	public VoucherPayment(long voucherId, String refTypeId) {
		this.voucherId = voucherId;
		this.refTypeId = refTypeId;
	}

	public VoucherPayment(long voucherId, String refTypeId, String refNo, Double netAmount, Double paidAmount,
			Date createdDate, Date updatedDate) {
		this.voucherId = voucherId;
		this.refTypeId = refTypeId;
		this.refNo = refNo;
		this.netAmount = netAmount;
		this.paidAmount = paidAmount;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "voucher_id", nullable = false)
	public long getVoucherId() {
		return this.voucherId;
	}

	public void setVoucherId(long voucherId) {
		this.voucherId = voucherId;
	}

	@Column(name = "ref_type_id", nullable = false, length = 50)
	public String getRefTypeId() {
		return this.refTypeId;
	}

	public void setRefTypeId(String refTypeId) {
		this.refTypeId = refTypeId;
	}

	@Column(name = "ref_no", length = 50)
	public String getRefNo() {
		return this.refNo;
	}

	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}

	@Column(name = "net_amount", precision = 22, scale = 0)
	public Double getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(Double netAmount) {
		this.netAmount = netAmount;
	}

	@Column(name = "paid_amount", precision = 22, scale = 0)
	public Double getPaidAmount() {
		return this.paidAmount;
	}

	public void setPaidAmount(Double paidAmount) {
		this.paidAmount = paidAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_date", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_date", length = 10)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	/**
	 * @return the balance
	 */
	@Transient
	public Double getBalance() {
		return balance;
	}

	/**
	 * @param balance the balance to set
	 */
	public void setBalance(Double balance) {
		this.balance = balance;
	}

	/**
	 * @return the gstNo
	 */
	@Transient
	public String getGstNo() {
		return gstNo;
	}

	/**
	 * @param gstNo the gstNo to set
	 */
	public void setGstNo(String gstNo) {
		this.gstNo = gstNo;
	}
	
	

}
